export const PATHS = {
  // auth routes
  root: "/",
  login: "/login",
  register: "/register",
  // admin routes
  adminDashboard: "/admin-dashboard",
  adminAnalytics: "/admin-analytics",
  adminCart: "/admin-cart",
  adminCategories: "/admin-categories",
  adminCheckout: "/admin-checkout",
  adminCmsAndSeo: "/admin-cms-seo",
  adminCollection: "/admin-collection",
  adminCollectionConditions: "/admin-collection-conditions",
  adminCouponsAndDiscounts: "/admin-coupons-and-discounts",
  adminCouriers: "/admin-couriers",
  adminCustomer: "/admin-customer",
  adminEmailMarketing: "/admin-email-marketing",
  adminInventoryManagement: "/admin-inventory-management",
  adminOrderManagement: "/admin-order-management",
  adminPayments: "/admin-payments",
  adminProductInventory: "/admin-product-inventory",
  adminProductManagement: "/admin-product-management",
  adminRefund: "/admin-refund",
  adminReplacement: "/admin-replacement",
  adminReviews: "/admin-reviews",
  adminShipments: "/admin-shipments",
  adminSupply: "/admin-supply",
  adminSupport: "/admin-support",
  adminAddProducts: "/admin-add-products",
  adminAddCategory: "/admin-add-category",
  adminAddAttributes: "/admin-add-attributes",
  adminAttribute: "/admin/attribute",
};
