export const PATHS = {
  // auth routes
  root: "/",
  login: "/login",
  register: "/register",
  permissionDenied: "/permission-denied",
  pageNotFound: "/page-not-found",
  // admin routes
  adminDashboard: "/admin/dashboard",
  adminCart: "/admin/cart",
  adminCategories: "/admin/categories",
  adminCheckout: "/admin/checkout",
  adminCmsAndSeo: "/admin/cms-seo",
  adminCollection: "/admin/collection",
  adminCollectionConditions: "/admin/collection-conditions",
  adminDiscounts: "/admin/discounts",
  adminCoupons: "/admin/coupons",
  adminCouriers: "/admin/couriers",
  adminCustomer: "/admin/customer",
  adminEmailMarketing: "/admin/email-marketing",
  adminInventoryManagement: "/admin/inventory-management",
  adminOrderManagement: "/admin/order-management",
  adminPayments: "/admin/payments",
  adminProductInventory: "/admin/product-inventory",
  adminProductManagement: "/admin/product-management",
  adminRefund: "/admin/refund",
  adminReplacement: "/admin/replacement",
  adminReviews: "/admin/reviews",
  adminShipments: "/admin/shipments",
  adminVendor: "/admin/vendor",
  adminSupport: "/admin/support",
  adminAddProducts: "/admin/product-management/add-products",
  adminAddCategory: "/admin/categories/add-category",
  adminAddAttributes: "/admin/attributes/add-attributes",
  adminAttribute: "/admin/attributes",
  adminAddDiscount: "/admin/discounts/add-discount",
  adminAddCoupon: "/admin/coupons/add-coupon",
  adminAddCollection: "/admin/collection/add-collection",
  adminCreateCustomer: "/admin/customer/create-customer",
  adminCreateVendor: "/admin/vendor/create-vendor",
  adminWishlist: "/admin/wishlist",

  // vendor routes
  vendorDashboard: "/vendor/dashboard",
  vendorProductManagement: "/vendor/product-management",
  vendorOrderManagement: "/vendor/order-management",
  vendorDiscounts: "/vendor/discounts",
  vendorCoupons: "/vendor/coupons",
  vendorCheckout: "/vendor/checkout",
  vendorProductInventory: "/vendor/product-inventory",
  vendorRefund: "/vendor/refund",
  vendorShipments: "/vendor/shipments",
  vendorCart: "/vendor/cart",
  vendorAddProducts: "/vendor/add-products",

  // customer routes
  customerDashboard: "/customer/dashboard",
  customerCheckouts: "/customer/checkouts",
  customerCart: "/customer/cart",
  customerOrders: "/customer/orders",
  customerPayments: "/customer/payments",
  customerProfile: "/customer/profile",
  customerRefunds: "/customer/refunds",
  customerReplacements: "/customer/replacements",
  customerWishlist: "/customer/wishlist",
};
